version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env.example

  node-agent:
    build: ./node_agent
    container_name: kpi_faas-node-agent
    ports:
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  auth-service:
    build: ./services/auth_service
    ports:
      - "50051:50051"
    env_file:
      - ./services/auth_service/.env

  runtime-service:
    build: ./services/runtime_service
    ports:
      - "50061:50061"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./services/runtime_service/.env

  function-service:
    build: ./services/function_service
    ports:
      - "50071:50071"
    env_file:
      - ./services/function_service/.env

  load-balancer-service:
    build: ./services/load_balancer_service
    ports:
      - "50011:50011"
    env_file:
      - ./services/load_balancer_service/.env

  crontab-trigger-service:
    build: ./services/crontab_trigger_service
    ports:
      - "50081:50081"
    env_file:
      - ./services/crontab_trigger_service/.env

  api-gateway-trigger-service:
    build: ./services/api_gateway_trigger_service
    ports:
      - "50091:50091"
    env_file:
      - ./services/api_gateway_trigger_service/.env

  image-repo:
    image: registry:2
    ports:
      - "5555:5000"
    volumes:
      - ./faas-registry:/var/lib/registry
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - "8080:80"
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://image-repo:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
